In [1]:
import pandas as pd 
import numpy as np

### 根据分隔符分割行

In [2]:
## 通过分隔符将行分割为更多行

def rowToRow(temp):
    temp_1=temp['输入关键词'].str.split('、',expand=True)
    temp_1=temp_1.stack()
    temp_1 = temp_1.reset_index(level=1,drop=True)
    temp_1.name='输入关键词'
    df_new = temp.drop(['输入关键词'], axis=1).join(temp_1)
    display(df_new)
    return df_new

In [7]:
test = pd.read_excel(io=r"C:\Users\TUNGEE\Desktop\产业链补充数据TEMP.xlsx")
test.info

<bound method DataFrame.info of       Unnamed: 0  股票名称             股票全称            社会统一信用代码    经营产品    股票代码  \
0              0  沙河股份       沙河实业股份有限公司                 NaN   房地产开发      14
1              1  ST深天  深圳市天地(集团)股份有限公司                 NaN   商品混凝土      23
2              2  ST深天  深圳市天地(集团)股份有限公司                 NaN    水泥制品      23
3              3  ST深天  深圳市天地(集团)股份有限公司                 NaN  机电设备维修      23
4              4  深南电A     深圳南山热电股份有限公司                 NaN      供电      37
...          ...   ...              ...                 ...     ...     ...
6305        6305  锦好医疗  惠州市锦好医疗科技股份有限公司  91441300581432767X     助听器  872925
6306        6306  锦好医疗  惠州市锦好医疗科技股份有限公司  91441300581432767X     雾化器  872925
6307        6307  锦好医疗  惠州市锦好医疗科技股份有限公司  91441300581432767X     气垫床  872925
6308        6308  九菱科技     荆州九菱科技股份有限公司  91421000178965352L  粉末冶金产品  873305
6309        6309  九菱科技     荆州九菱科技股份有限公司  91421000178965352L  磁性材料产品  873305

      上游关键词  下游关键词
0       NaN    NaN
1       NaN    NaN
2       NaN    NaN
3       NaN    NaN
4       NaN    NaN
...     ...    ...
6305    NaN    NaN
6306    NaN    NaN
6307    NaN    NaN
6308    NaN    NaN
6309    NaN    NaN

[6310 rows x 8 columns]>

In [14]:
display(test)
df_new = rowToRow(test)
df_new.to_excel(r"C:\Users\TUNGEE\Desktop\补充数据.xlsx")

,Unnamed: 0,股票名称,股票全称,社会统一信用代码,经营产品,股票代码,上游关键词,下游关键词
0,0,沙河股份,沙河实业股份有限公司,NaN,房地产开发,14,NaN,NaN
1,1,ST深天,深圳市天地(集团)股份有限公司,NaN,商品混凝土,23,NaN,NaN
2,2,ST深天,深圳市天地(集团)股份有限公司,NaN,水泥制品,23,NaN,NaN
3,3,ST深天,深圳市天地(集团)股份有限公司,NaN,机电设备维修,23,NaN,NaN
4,4,深南电A,深圳南山热电股份有限公司,NaN,供电,37,NaN,NaN
...,...,...,...,...,...,...,...,...
6305,6305,锦好医疗,惠州市锦好医疗科技股份有限公司,91441300581432767X,助听器,872925,NaN,NaN
6306,6306,锦好医疗,惠州市锦好医疗科技股份有限公司,91441300581432767X,雾化器,872925,NaN,NaN
6307,6307,锦好医疗,惠州市锦好医疗科技股份有限公司,91441300581432767X,气垫床,872925,NaN,NaN
6308,6308,九菱科技,荆州九菱科技股份有限公司,91421000178965352L,粉末冶金产品,873305,NaN,NaN
6309,6309,九菱科技,荆州九菱科技股份有限公司,91421000178965352L,磁性材料产品,873305,NaN,NaN

,Unnamed: 0,股票名称,股票全称,社会统一信用代码,股票代码,上游关键词,下游关键词,经营产品
0,0,沙河股份,沙河实业股份有限公司,NaN,14,NaN,NaN,房地产开发
1,1,ST深天,深圳市天地(集团)股份有限公司,NaN,23,NaN,NaN,商品混凝土
2,2,ST深天,深圳市天地(集团)股份有限公司,NaN,23,NaN,NaN,水泥制品
3,3,ST深天,深圳市天地(集团)股份有限公司,NaN,23,NaN,NaN,机电设备维修
4,4,深南电A,深圳南山热电股份有限公司,NaN,37,NaN,NaN,供电
...,...,...,...,...,...,...,...,...
6305,6305,锦好医疗,惠州市锦好医疗科技股份有限公司,91441300581432767X,872925,NaN,NaN,助听器
6306,6306,锦好医疗,惠州市锦好医疗科技股份有限公司,91441300581432767X,872925,NaN,NaN,雾化器
6307,6307,锦好医疗,惠州市锦好医疗科技股份有限公司,91441300581432767X,872925,NaN,NaN,气垫床
6308,6308,九菱科技,荆州九菱科技股份有限公司,91421000178965352L,873305,NaN,NaN,粉末冶金产品
6309,6309,九菱科技,荆州九菱科技股份有限公司,91421000178965352L,873305,NaN,NaN,磁性材料产品

In [12]:

def rowToRow(temp):
    temp_1=temp['经营产品'].str.split('，',expand=True)
    temp_1=temp_1.stack()
    temp_1 = temp_1.reset_index(level=1,drop=True)
    temp_1.name='经营产品'
    df_new = temp.drop(['经营产品'], axis=1).join(temp_1)
    display(df_new)
    return df_new

In [21]:
temp = pd.read_excel(io=r"C:\Users\TUNGEE\Desktop\企业补充数据.xlsx")
temp_1=temp['输入关键词'].str.split('、',expand=True)
temp_1=temp_1.stack()
temp_1 = temp_1.reset_index(level=1,drop=True)
temp_1.name='输入关键词'
display(temp_1)
display(temp)
df_new = temp.drop(['输入关键词'], axis=1).join(temp_1)
display(df_new)

0         房地产开发
1         商品混凝土
2          水泥制品
3        机电设备维修
4            供电
         ...
1391       硬件产品
1392    高精密螺栓组件
1392        高强度
1392      耐低温螺栓
1392       自锁螺母
Name: 输入关键词, Length: 1989, dtype: object

      Unnamed: 0   股票代码_  股票名称                   输入关键词  上游关键词  下游关键词
0           4776      14  沙河股份                   房地产开发    NaN    NaN
1           4777      23  ST深天                   商品混凝土    NaN    NaN
2           4777      23  ST深天                    水泥制品    NaN    NaN
3           4777      23  ST深天                  机电设备维修    NaN    NaN
4           4778      37  深南电A                      供电    NaN    NaN
...          ...     ...   ...                     ...    ...    ...
1388        5275  871857  泓禧科技        极细同轴线、极细铁氟龙线、电子线    NaN    NaN
1389        5276  871970  大禹生物       微生态制剂、饲用酶制剂、饲料、兽药    NaN    NaN
1390        5277  872392  佳合科技       展示架、彩盒、手提袋、礼品盒、彩卡    NaN    NaN
1391        5278  872953  国子软件               软件产品、硬件产品    NaN    NaN
1392        5279  873169  七丰精工  高精密螺栓组件、高强度、耐低温螺栓、自锁螺母    NaN    NaN

[1393 rows x 6 columns]

      Unnamed: 0   股票代码_  股票名称  上游关键词  下游关键词    输入关键词
0           4776      14  沙河股份    NaN    NaN    房地产开发
1           4777      23  ST深天    NaN    NaN    商品混凝土
2           4777      23  ST深天    NaN    NaN     水泥制品
3           4777      23  ST深天    NaN    NaN   机电设备维修
4           4778      37  深南电A    NaN    NaN       供电
...          ...     ...   ...    ...    ...      ...
1391        5278  872953  国子软件    NaN    NaN     硬件产品
1392        5279  873169  七丰精工    NaN    NaN  高精密螺栓组件
1392        5279  873169  七丰精工    NaN    NaN      高强度
1392        5279  873169  七丰精工    NaN    NaN    耐低温螺栓
1392        5279  873169  七丰精工    NaN    NaN     自锁螺母

[1989 rows x 6 columns]